import  GlobalProvider from '@/context/Globalcontext'
import './globals.css'
import { Inter } from 'next/font/google'
import Mainlayout from '@/app/mainlayout'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NHD Music and art Pvt Ltd',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`{inter.className} `}>
      <GlobalProvider>
        <Mainlayout>{children}</Mainlayout>
      </GlobalProvider>
      </body>
    </html>
  )
}
